config/routes.rb
# require 'sidekiq/web'

Rails.application.routes.draw do

  # namespace :api, :defaults => {:format => 'json'} do
  #   devise_for :users
  #   # get "courses" => 'courses#index'
  #   # devise_for :users do 
  #   #   delete 'api/users/sign_out', to: 'api/sessions#destroy'
  #   # end
  # end

  resources :coordenadors, path: :coordenadores
  resources :offers do
    collection do
      patch :load_grid
      get :ptd_index, constraints: lambda { |req| req.format == :json }
      # get '/course_plans/:user_id', to: 'plans#course_plans'
      # patch :load_grid_disciplines
    end
    member do
      post :gerar_planos_lote
    end
    resources :offer_disciplines do
      resources :plans do
        member do
          get 'copy'
          get 'copy_outra_oferta'
          post 'aprovar'
          get 'enviar_aviso_nupe'
        end
      end
    end
  end

  get "planos/:id/parecer" => 'plans#plano_parecer', :as => :plano_parecer
  get 'planos/:course_id', to: 'plans#planos_curso', as: 'planos_curso'
  get 'planos', to: 'plans#planos_professor', as: 'planos_professor'
  # put 'update_perfils/:users', to: 'user#update_perfils', as: 'update_perfils_users'
  get 'aprovacao', to: 'plans#get_planos_aprovar', as: 'get_planos_aprovar'
  # get 'aprovacao_user', to: 'plans#get_planos_user_aprovar', as: 'get_planos_user_aprovar'
  # put 'aprovacao/:plan', to: 'plans#aprovar', as: 'aprovar_plano'

  # Área pública para planos
  get 'plans/public/index', to: 'plans#public_index', as: 'public_index'
  post 'plans/public/index', to: 'plans#public_index_course', as: 'public_index_course'

  get 'plans/public/:course_id/disciplinas', to: 'plans#public_disciplinas', as: 'public_disciplinas'
  post 'plans/public/:course_id/disciplinas', to: 'plans#public_disciplina_planos', as: 'public_disciplina_planos'

  get 'plans/public/:course_id/:discipline_id/planos', to: 'plans#public_curso_disciplina_planos', as: 'public_curso_disciplina_planos'
  # post 'plans/public/:course_id/:discipline_id/planos', to: 'plans#public_curso_disciplina_planos', as: 'public_curso_disciplina_planos'

  get 'plans/publico/index', to: 'plans#publico_index', as: 'publico_index'
  post 'plans/publico/index', to: 'plans#publico_index_planos', as: 'publico_index_planos'
  get 'plans/admin/enviar_aviso_nupe', to: 'plans#enviar_aviso_nupe', as: 'admin_enviar_aviso_nupe'
  match '/pesquisar' => 'plans#pesquisar', as: 'pesquisar_planos', via: [:get, :post]

  # Coordenação de curso
  match '/ofertas_coordenador' => 'offers#pesquisar', as: 'ofertas_coordenador', via: [:get, :post]
  match '/ofertas_coordenador/enviar_aviso_plano_pendente' => 'offers#enviar_aviso_plano_pendente', as: 'coor_enviar_aviso_plano_pendente', via: [:get]
  match '/ofertas_coordenador/enviar_aviso_planos_pendentes' => 'offers#enviar_aviso_plano_pendente', as: 'coor_enviar_aviso_planos_pendentes', via: [:get]

  resources :grid_disciplines
  resources :grids, except: [:destroy] do
    member do
      get 'copy'
    end
    collection do
      get :importar
      post  :importar
    end
    resources :grid_disciplines
  end
  resources :turmas
  resources :course_offers
  resources :courses
  resources :course_modalities
  resources :course_formats
  resources :disciplines, path: 'disciplinas'
  resources :permissao_telas
  resources :permissaos
  resources :perfils
  resources :roles
  resources :perfil_roles, except: [:show]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Configurar para que a tela inicial seja a tela de login, caso não esteja autenticado
  devise_for :users, 
    :controllers => {:registrations => "registrations" },
    skip: [:sessions]
    as :user do
      get 'login', to: 'devise/sessions#new', as: :new_user_session
      post 'login', to: 'devise/sessions#create', as: :user_session
      match 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
  end
  # unauthenticated do
  #   as :user do
  #     root to: 'devise/sessions#new'
  #   end
  # end

  resources :users do
    collection do
      put 'update_perfils'
    end
  end

  # Interface para acessar as tarefas em background através do sidekiq
  # authenticate :user, lambda { |u| u.admin? } do
  #   mount Sidekiq::Web => '/sidekiq' if Rails.env.production? #|| Rails.env.staging?
  # end

  # endereço para ver os e-mails no ambiente de aprovação (staging)
  # mount LetterOpenerWeb::Engine, at: "/mails" if Rails.env.staging? || Rails.env.development?

  root to: 'visitors#index'

end

app/models/discipline.rb
class Discipline < ApplicationRecord
  belongs_to :user
  has_many :grid_disciplines
  # has_many :grids#, :through => :grid_disciplines

  validates :title, :sigla, :user, presence:true
  validates :title, uniqueness:true

  def decorate
    @decorate ||= DisciplineDecorator.new self
  end
end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  before_action :set_discipline, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  responders :flash

  # add_breadcrumb (I18n.t "helpers.links.pages.#{controller_name}", default: controller_name), :disciplines_path

  # GET /disciplines
  # GET /disciplines.json
  def index
    # @disciplines = Discipline.all
    respond_to do |format|
      format.html
      format.json { render json: DisciplineDatatable.new(view_context) }
    end
  end

  def sortable_columns
    ["id", "title", "sigla", "active"]
  end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : "title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  # GET /disciplines/1
  # GET /disciplines/1.json
  # def show
  # end

  # GET /disciplines/new
  def new
    @discipline = Discipline.new
  end

  # GET /disciplines/1/edit
  def edit
  end

  # POST /disciplines
  # POST /disciplines.json
  def create
    @discipline = Discipline.new(discipline_params)
    @discipline.user = current_user

    respond_to do |format|
      if @discipline.save
        format.html { redirect_to disciplines_url, notice: t('flash.actions.create.notice', resource_name: controller_name.classify.constantize.model_name.human) }
        format.json { render :index, status: :created, location: @discipline }
      else
        format.html { render :new }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplines/1
  # PATCH/PUT /disciplines/1.json
  def update
    respond_to do |format|
      @discipline.user = current_user
      if @discipline.update(discipline_params)
        format.html { redirect_to disciplines_url, notice: t('flash.actions.update.notice', resource_name: controller_name.classify.constantize.model_name.human) }
        format.json { render :index, status: :ok, location: @discipline }
      else
        format.html { render :edit }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplines/1
  # DELETE /disciplines/1.json
  def destroy
    @discipline.destroy
    respond_to do |format|
      format.html { redirect_to disciplines_url, notice: t('flash.actions.destroy.notice', resource_name: controller_name.classify.constantize.model_name.human) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discipline
      @discipline = Discipline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discipline_params
      params.require(:discipline).permit(:title, :sigla, :active, :user_id, :especial)
    end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
  # Retorna apenas os cursos onde o professor tenha algum plano de ensino ofertado
  def disciplinas_curso_e_por_professor
    if user_signed_in? && is_professor?
      OfferDiscipline.distinct.joins(grid_discipline: {grid: :course }).
        joins(grid_discipline: :discipline).
        where('offer_disciplines.active is true').
        where('courses.id = ?', params[:course_id]).
        where('offer_disciplines.user_id = ?', current_user.id).pluck('disciplines.id, disciplines.title')
    end
  end
end

app/views/disciplines/_form.html.erb
<%= bootstrap_form_for(discipline, local:true) do |form| %>
  <!-- <= render partial: 'shared/error_messages', locals: {obj: @discipline} %> -->
  <%= error_messages_for(discipline) %>

    <%= form.text_field :title, id: :discipline_title, placeholder:true, autofocus:true %>
    <%= form.text_field :sigla, id: :discipline_sigla, placeholder:true %>
    <div class="form-group">
      <%= form.check_box :active, id: :discipline_active %>
    </div>
    <div class="form-group">
      <%= form.check_box :especial, id: :discipline_especial %>
      <span class="help-block">Marque a opção ESPECIAL caso ementa, objetivo geral e referêcias bibliográficas sejam responsabilidade do professor.</span>
    </div>

    <%= form.submit class: 'btn btn-primary' %>

<% end %>

app/views/disciplines/edit.html.erb
<%- model = Discipline %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= t('helpers.titles.edit', model: model.model_name.human.downcase) %>
    </h3>
  </div>
  <div class="panel-body">
    <%= render 'form', discipline: @discipline %>
  </div>
  <div class="panel-footer">
    <!-- <= link_to t('helpers.links.back'), discipline_path %> -->
    <%= link_to disciplines_path, class: 'btn btn-sm btn-default' do %>
      <i class='fa fa-list fa-2'></i>
      <%= t('helpers.links.back') %>
    <% end %>
    <%= link_to @discipline, class: 'btn btn-sm btn-info' do %>
      <i class="fa fa-info fa-2" aria-hidden="true"></i>
      <%= t('helpers.links.show') %>
    <% end %>
  </div>
</div>

app/views/disciplines/index.html.erb
<%- model = Discipline -%>
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <h3 class="panel-title pull-left">
      <%= link_to new_discipline_path do %>
        <i class="fa fa-plus" aria-hidden="true"></i>
        <%= t '.title', :default => model.model_name.human %>
      <% end %>
    </h3>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <%= content_tag :table, id: 'disciplines_datatable', class: 'table table-striped table-bordered', data: { url: disciplines_path(format: :json)} do %>
        <thead>
          <tr>
            <th><%= model.human_attribute_name(:title) %></th>
            <th><%= model.human_attribute_name(:sigla) %></th>
            <th><%= model.human_attribute_name(:active) %></th>
            <th><%= model.human_attribute_name(:especial) %></th>
            <!-- <th></th> -->
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody></tbody>
      <%end%>
    </div>
  </div>
  <div class="panel-footer clearfix">
    <div class="">
      <%= link_to new_discipline_path do %>
        <i class="fa fa-plus" aria-hidden="true"></i>
        <%= t('.new', :default => t("helpers.titles.new", model: model.model_name.human.downcase)) %>
      <% end %>
    </div>
  </div>
</div>

app/views/disciplines/new.html.erb
<%- model = Discipline %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= t('helpers.titles.new', model: model.model_name.human.downcase) %>
    </h3>
  </div>
  <div class="panel-body">
    <%= render 'form', discipline: @discipline %>
  </div>
  <div class="panel-footer">
    <%= link_to t('helpers.links.back'), disciplines_path %>
  </div>
</div>

app/views/disciplines/show.html.erb
<div class="page-header">
  <%= link_to disciplines_path, class: 'btn btn-default' do %>
    <i class='fa fa-list fa-2'></i>
    Back
  <% end %>
  <%= link_to edit_discipline_path(@discipline), class: 'btn btn-primary' do %>
    <i class='fa fa-pencil-square-o fa-2'></i>
    Edit
  <% end %>
  <h1>Show discipline</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @discipline.title %></dd>

  <dt>Sigla:</dt>
  <dd><%= @discipline.sigla %></dd>

  <dt>Active:</dt>
  <dd><%= @discipline.active %></dd>

  <dt>User:</dt>
  <dd><%= @discipline.user %></dd>

</dl>