config/routes.rb
# require 'sidekiq/web'

Rails.application.routes.draw do

  # namespace :api, :defaults => {:format => 'json'} do
  #   devise_for :users
  #   # get "courses" => 'courses#index'
  #   # devise_for :users do 
  #   #   delete 'api/users/sign_out', to: 'api/sessions#destroy'
  #   # end
  # end

  resources :coordenadors, path: :coordenadores
  resources :offers do
    collection do
      patch :load_grid
      get :ptd_index, constraints: lambda { |req| req.format == :json }
      # get '/course_plans/:user_id', to: 'plans#course_plans'
      # patch :load_grid_disciplines
    end
    member do
      post :gerar_planos_lote
    end
    resources :offer_disciplines do
      resources :plans do
        member do
          get 'copy'
          get 'copy_outra_oferta'
          post 'aprovar'
          get 'enviar_aviso_nupe'
        end
      end
    end
  end

  get "planos/:id/parecer" => 'plans#plano_parecer', :as => :plano_parecer
  get 'planos/:course_id', to: 'plans#planos_curso', as: 'planos_curso'
  get 'planos', to: 'plans#planos_professor', as: 'planos_professor'
  # put 'update_perfils/:users', to: 'user#update_perfils', as: 'update_perfils_users'
  get 'aprovacao', to: 'plans#get_planos_aprovar', as: 'get_planos_aprovar'
  # get 'aprovacao_user', to: 'plans#get_planos_user_aprovar', as: 'get_planos_user_aprovar'
  # put 'aprovacao/:plan', to: 'plans#aprovar', as: 'aprovar_plano'

  # Área pública para planos
  get 'plans/public/index', to: 'plans#public_index', as: 'public_index'
  post 'plans/public/index', to: 'plans#public_index_course', as: 'public_index_course'

  get 'plans/public/:course_id/disciplinas', to: 'plans#public_disciplinas', as: 'public_disciplinas'
  post 'plans/public/:course_id/disciplinas', to: 'plans#public_disciplina_planos', as: 'public_disciplina_planos'

  get 'plans/public/:course_id/:discipline_id/planos', to: 'plans#public_curso_disciplina_planos', as: 'public_curso_disciplina_planos'
  # post 'plans/public/:course_id/:discipline_id/planos', to: 'plans#public_curso_disciplina_planos', as: 'public_curso_disciplina_planos'

  get 'plans/publico/index', to: 'plans#publico_index', as: 'publico_index'
  post 'plans/publico/index', to: 'plans#publico_index_planos', as: 'publico_index_planos'
  get 'plans/admin/enviar_aviso_nupe', to: 'plans#enviar_aviso_nupe', as: 'admin_enviar_aviso_nupe'
  match '/pesquisar' => 'plans#pesquisar', as: 'pesquisar_planos', via: [:get, :post]

  # Coordenação de curso
  match '/ofertas_coordenador' => 'offers#pesquisar', as: 'ofertas_coordenador', via: [:get, :post]
  match '/ofertas_coordenador/enviar_aviso_plano_pendente' => 'offers#enviar_aviso_plano_pendente', as: 'coor_enviar_aviso_plano_pendente', via: [:get]
  match '/ofertas_coordenador/enviar_aviso_planos_pendentes' => 'offers#enviar_aviso_plano_pendente', as: 'coor_enviar_aviso_planos_pendentes', via: [:get]

  resources :grid_disciplines
  resources :grids, except: [:destroy] do
    member do
      get 'copy'
    end
    collection do
      get :importar
      post  :importar
    end
    resources :grid_disciplines
  end
  resources :turmas
  resources :course_offers
  resources :courses
  resources :course_modalities
  resources :course_formats
  resources :disciplines, path: 'disciplinas'
  resources :permissao_telas
  resources :permissaos
  resources :perfils
  resources :roles
  resources :perfil_roles, except: [:show]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Configurar para que a tela inicial seja a tela de login, caso não esteja autenticado
  devise_for :users, 
    :controllers => {:registrations => "registrations" },
    skip: [:sessions]
    as :user do
      get 'login', to: 'devise/sessions#new', as: :new_user_session
      post 'login', to: 'devise/sessions#create', as: :user_session
      match 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
  end
  # unauthenticated do
  #   as :user do
  #     root to: 'devise/sessions#new'
  #   end
  # end

  resources :users do
    collection do
      put 'update_perfils'
    end
  end

  # Interface para acessar as tarefas em background através do sidekiq
  # authenticate :user, lambda { |u| u.admin? } do
  #   mount Sidekiq::Web => '/sidekiq' if Rails.env.production? #|| Rails.env.staging?
  # end

  # endereço para ver os e-mails no ambiente de aprovação (staging)
  # mount LetterOpenerWeb::Engine, at: "/mails" if Rails.env.staging? || Rails.env.development?

  root to: 'visitors#index'

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  include ApplicationHelper

  def index
    # if is_professor?
    #
    #   curso_ids = current_user.offer_disciplines.joins(:offer => :grid).
    #     where(active:true).where('offers.active = ?', true).
    #     pluck('grids.course_id').uniq
    #
    #   @cursos = Course.where(id: curso_ids)
    # end

    if is_professor?
      redirect_to planos_professor_path
    # else
    #   @class_panel1 = 'col-md-12'
    #   @class_panel2 = ''
    #
    #   @class_panel1 = 'col-md-8' if (is_professor?) || (can? :aprovar_reprovar, Plan)
    #   @class_panel2 = 'col-md-4' if (is_professor?) || (can? :aprovar_reprovar, Plan)
    end


  end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/visitors/pesquisar/_form.html.erb
<!-- <= form_with(url: pesquisar_planos_path, local:true, remote:false, method: :post) do |f| %>

  <div class="form-group col-md-6">
    <= label_tag :curso_id, '* Curso' %>
    <= select_tag :curso_id, options_from_collection_for_select(Course.where(active:true).order(:name), "id", "name", params[:curso_id]), id: :curso_id, class: 'form-control', prompt:'Selecione o curso', required:true, autofocus:true %>
  </div>

  <div class="form-group col-md-2">
    <= label_tag :turma, 'Turma' %>
    <= text_field :turma, params[:turma], id: :turma, name: :turma, class: 'form-control', placeholder:'Turma' %>
  </div>

  <div class="form-group col-md-2">
    <= label_tag :year, 'Ano da Oferta' %>
    <= text_field :year, params[:year], id: :year, name: :year, class: 'form-control', placeholder:'Ano da Oferta' %>
  </div>

  <div class="form-group col-md-2">
    <label for=""></label>
    <= f.submit 'Pesquisar', class: 'btn btn-xs btn-search btn-primary form-control' %>
  </div>

< end %> -->
  <!-- <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Área Pública - Planos de Ensino</h3>
    </div>
    <div class="panel-body">

    </div>
  </div> -->

  <div class="table-responsive">
    <%= content_tag :table, id: 'planos_pesquisar_datatable',
        class: 'table table-striped table-condensed',
        data: { url: pesquisar_planos_path(format: :json)} do %>
      <caption class="well-sm text-center alert text-primary">
        Área Pública - Planos de Ensino
      </caption>
      <thead class="bg-primary">
        <tr>
          <th><%= t Course.model_name.human %></th>
          <th><%= t Offer.model_name.human %></th>
          <!-- <th><= t Offer.human_attribute_name(:turma) %></th> -->
          <th><%= t Discipline.model_name.human %></th>
          <th>Professor</th>
          <%# <th>Detalhes</th> %>
          <th>Imprimir</th>
        </tr>
      </thead>
      <tbody></tbody>
    <% end %>
  </div>

app/views/visitors/pesquisar/pesquisar.js.erb
$('div#pesquisar_planos').html("<%= escape_javascript(render partial: 'visitors/pesquisar/form', locals: { cursos: @cursos, params: params  } ) %>");