config/routes.rb
# require 'sidekiq/web'

Rails.application.routes.draw do

  # namespace :api, :defaults => {:format => 'json'} do
  #   devise_for :users
  #   # get "courses" => 'courses#index'
  #   # devise_for :users do 
  #   #   delete 'api/users/sign_out', to: 'api/sessions#destroy'
  #   # end
  # end

  resources :coordenadors, path: :coordenadores
  resources :offers do
    collection do
      patch :load_grid
      get :ptd_index, constraints: lambda { |req| req.format == :json }
      # get '/course_plans/:user_id', to: 'plans#course_plans'
      # patch :load_grid_disciplines
    end
    member do
      post :gerar_planos_lote
    end
    resources :offer_disciplines do
      resources :plans do
        member do
          get 'copy'
          get 'copy_outra_oferta'
          post 'aprovar'
          get 'enviar_aviso_nupe'
        end
      end
    end
  end

  get "planos/:id/parecer" => 'plans#plano_parecer', :as => :plano_parecer
  get 'planos/:course_id', to: 'plans#planos_curso', as: 'planos_curso'
  get 'planos', to: 'plans#planos_professor', as: 'planos_professor'
  # put 'update_perfils/:users', to: 'user#update_perfils', as: 'update_perfils_users'
  get 'aprovacao', to: 'plans#get_planos_aprovar', as: 'get_planos_aprovar'
  # get 'aprovacao_user', to: 'plans#get_planos_user_aprovar', as: 'get_planos_user_aprovar'
  # put 'aprovacao/:plan', to: 'plans#aprovar', as: 'aprovar_plano'

  # Área pública para planos
  get 'plans/public/index', to: 'plans#public_index', as: 'public_index'
  post 'plans/public/index', to: 'plans#public_index_course', as: 'public_index_course'

  get 'plans/public/:course_id/disciplinas', to: 'plans#public_disciplinas', as: 'public_disciplinas'
  post 'plans/public/:course_id/disciplinas', to: 'plans#public_disciplina_planos', as: 'public_disciplina_planos'

  get 'plans/public/:course_id/:discipline_id/planos', to: 'plans#public_curso_disciplina_planos', as: 'public_curso_disciplina_planos'
  # post 'plans/public/:course_id/:discipline_id/planos', to: 'plans#public_curso_disciplina_planos', as: 'public_curso_disciplina_planos'

  get 'plans/publico/index', to: 'plans#publico_index', as: 'publico_index'
  post 'plans/publico/index', to: 'plans#publico_index_planos', as: 'publico_index_planos'
  get 'plans/admin/enviar_aviso_nupe', to: 'plans#enviar_aviso_nupe', as: 'admin_enviar_aviso_nupe'
  match '/pesquisar' => 'plans#pesquisar', as: 'pesquisar_planos', via: [:get, :post]

  # Coordenação de curso
  match '/ofertas_coordenador' => 'offers#pesquisar', as: 'ofertas_coordenador', via: [:get, :post]
  match '/ofertas_coordenador/enviar_aviso_plano_pendente' => 'offers#enviar_aviso_plano_pendente', as: 'coor_enviar_aviso_plano_pendente', via: [:get]
  match '/ofertas_coordenador/enviar_aviso_planos_pendentes' => 'offers#enviar_aviso_plano_pendente', as: 'coor_enviar_aviso_planos_pendentes', via: [:get]

  resources :grid_disciplines
  resources :grids, except: [:destroy] do
    member do
      get 'copy'
    end
    collection do
      get :importar
      post  :importar
    end
    resources :grid_disciplines
  end
  resources :turmas
  resources :course_offers
  resources :courses
  resources :course_modalities
  resources :course_formats
  resources :disciplines, path: 'disciplinas'
  resources :permissao_telas
  resources :permissaos
  resources :perfils
  resources :roles
  resources :perfil_roles, except: [:show]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Configurar para que a tela inicial seja a tela de login, caso não esteja autenticado
  devise_for :users, 
    :controllers => {:registrations => "registrations" },
    skip: [:sessions]
    as :user do
      get 'login', to: 'devise/sessions#new', as: :new_user_session
      post 'login', to: 'devise/sessions#create', as: :user_session
      match 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
  end
  # unauthenticated do
  #   as :user do
  #     root to: 'devise/sessions#new'
  #   end
  # end

  resources :users do
    collection do
      put 'update_perfils'
    end
  end

  # Interface para acessar as tarefas em background através do sidekiq
  # authenticate :user, lambda { |u| u.admin? } do
  #   mount Sidekiq::Web => '/sidekiq' if Rails.env.production? #|| Rails.env.staging?
  # end

  # endereço para ver os e-mails no ambiente de aprovação (staging)
  # mount LetterOpenerWeb::Engine, at: "/mails" if Rails.env.staging? || Rails.env.development?

  root to: 'visitors#index'

end

app/models/perfil_role.rb
class PerfilRole < ApplicationRecord
  include PermissaosHelper
  belongs_to :perfil
  belongs_to :role

  validates :perfil_id, :role_id, presence:true
  validates :perfil_id, :role_id, uniqueness: {scope: [:perfil_id, :role_id]}
end

app/controllers/perfil_roles_controller.rb
class PerfilRolesController < ApplicationController
  before_action :set_perfil_role, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # before_action :admin_only
  load_and_authorize_resource
  responders :flash

  # add_breadcrumb (I18n.t "helpers.links.pages.#{controller_name}", default: controller_name), :roles_path

  # GET /perfil_roles
  # GET /perfil_roles.json
  def index
    # @perfil_roles = PerfilRole.all
    respond_to do |format|
      format.html
      format.json { render json: PerfilRoleDatatable.new(view_context) }
    end
  end

  # GET /perfil_roles/1
  # GET /perfil_roles/1.json
  # def show
  # end

  # GET /perfil_roles/new
  def new
    @perfil_role = PerfilRole.new
  end

  # GET /perfil_roles/1/edit
  def edit
  end

  # POST /perfil_roles
  # POST /perfil_roles.json
  def create
    @perfil_role = PerfilRole.new(perfil_role_params)

    respond_to do |format|
      if @perfil_role.save
        format.html { redirect_to perfil_roles_url, notice: t('flash.actions.create.notice', resource_name: controller_name.classify.constantize.model_name.human) }
        format.json { render :index, status: :created, location: @perfil_role }
      else
        format.html { render :new }
        format.json { render json: @perfil_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perfil_roles/1
  # PATCH/PUT /perfil_roles/1.json
  def update
    respond_to do |format|
      if @perfil_role.update(perfil_role_params)
        format.html { redirect_to perfil_roles_url, notice: t('flash.actions.update.notice', resource_name: controller_name.classify.constantize.model_name.human) }
        format.json { render :index, status: :ok, location: @perfil_role }
      else
        format.html { render :edit }
        format.json { render json: @perfil_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perfil_roles/1
  # DELETE /perfil_roles/1.json
  def destroy
    @perfil_role.destroy
    respond_to do |format|
      format.html { redirect_to perfil_roles_url, notice: t('flash.actions.destroy.notice', resource_name: controller_name.classify.constantize.model_name.human) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perfil_role
      @perfil_role = PerfilRole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def perfil_role_params
      params.require(:perfil_role).permit(:perfil_id, :role_id)
    end

    def admin_only
      unless current_user.admin?
        redirect_to root_path, :alert => "Acesso negado. Você não tem permissão para acessar este recurso."
      end
    end
end

app/helpers/perfil_roles_helper.rb
module PerfilRolesHelper
end

app/views/perfil_roles/_form.html.erb
<!-- <= bootstrap_form_for(perfil_role, local:true, html: { class: "", role: "form" }) do |f| %>
  <= error_messages_for(perfil_role) %>


    <= f.select :perfil_id, Perfil.where(idativo:true).collect { |c| [ c.name, c.id] },
      { prompt:true, id: :perfil_role_perfil_id }, { class: 'select2', autofocus:true } %>
    <= f.select :role_id, Role.order(:name).collect { |c| [ c.name, c.id] },
      { prompt:true, id: :perfil_role_role_id }, { class: 'select2' } %>

    <= f.submit class: "btn btn-primary" %>
< end %> -->

app/views/perfil_roles/edit.html.erb
<%- model = PerfilRole %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= t('helpers.titles.edit', model: model.model_name.human.downcase) %>
    </h3>
  </div>
  <div class="panel-body">
    <%= render 'form', perfil_role: @perfil_role %>
  </div>
  <div class="panel-footer">
    <!-- <= link_to t('helpers.links.back'), discipline_path %> -->
    <%= link_to perfil_roles_path, class: 'btn btn-sm btn-default' do %>
      <i class='fa fa-list fa-2'></i>
      <%= t('helpers.links.back') %>
    <% end %>
    <%= link_to @perfil_role, class: 'btn btn-sm btn-info' do %>
      <i class="fa fa-info fa-2" aria-hidden="true"></i>
      <%= t('helpers.links.show') %>
    <% end %>
  </div>
</div>

app/views/perfil_roles/index.html.erb
<%- model = PerfilRole %>

<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <h3 class="panel-title pull-left">
      <%= link_to new_perfil_role_path do %>
        <i class="fa fa-plus" aria-hidden="true"></i>
        <%= t '.title', :default => model.model_name.human.pluralize.titleize %>
      <% end %>
    </h3>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <%= content_tag :table, id: "perfil_roles_datatable", class: 'table table-striped table-bordered', role: :datatable, data: { url: perfil_roles_path(format: :json)} do %>
        <thead>
          <tr>
            <th><%= model.human_attribute_name(:perfil) %></th>
            <th><%= model.human_attribute_name(:role) %></th>
            <!-- <th></th> -->
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody></tbody>
      <% end %>
    </div>
  </div>
  <div class="panel-footer clearfix">
    <div class="">
      <%= link_to new_perfil_role_path do %>
        <i class="fa fa-plus" aria-hidden="true"></i>
        <%= t('.new', :default => t("helpers.titles.new", model: model.model_name.human.downcase )) %>
      <% end %>
    </div>
    <div class="pull-right">

    </div>
  </div>
</div>

app/views/perfil_roles/new.html.erb
<%- model = PerfilRole %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= t('helpers.titles.new', model: model) %>
    </h3>
  </div>
  <div class="panel-body">
    <%= render 'form', perfil_role: @perfil_role %>
  </div>
  <div class="panel-footer">
    <%= link_to t('helpers.links.back'), perfil_roles_path %>
  </div>
</div>