config/routes.rb
# require 'sidekiq/web'

Rails.application.routes.draw do

  # namespace :api, :defaults => {:format => 'json'} do
  #   devise_for :users
  #   # get "courses" => 'courses#index'
  #   # devise_for :users do 
  #   #   delete 'api/users/sign_out', to: 'api/sessions#destroy'
  #   # end
  # end

  resources :coordenadors, path: :coordenadores
  resources :offers do
    collection do
      patch :load_grid
      get :ptd_index, constraints: lambda { |req| req.format == :json }
      # get '/course_plans/:user_id', to: 'plans#course_plans'
      # patch :load_grid_disciplines
    end
    member do
      post :gerar_planos_lote
    end
    resources :offer_disciplines do
      resources :plans do
        member do
          get 'copy'
          get 'copy_outra_oferta'
          post 'aprovar'
          get 'enviar_aviso_nupe'
        end
      end
    end
  end

  get "planos/:id/parecer" => 'plans#plano_parecer', :as => :plano_parecer
  get 'planos/:course_id', to: 'plans#planos_curso', as: 'planos_curso'
  get 'planos', to: 'plans#planos_professor', as: 'planos_professor'
  # put 'update_perfils/:users', to: 'user#update_perfils', as: 'update_perfils_users'
  get 'aprovacao', to: 'plans#get_planos_aprovar', as: 'get_planos_aprovar'
  # get 'aprovacao_user', to: 'plans#get_planos_user_aprovar', as: 'get_planos_user_aprovar'
  # put 'aprovacao/:plan', to: 'plans#aprovar', as: 'aprovar_plano'

  # Área pública para planos
  get 'plans/public/index', to: 'plans#public_index', as: 'public_index'
  post 'plans/public/index', to: 'plans#public_index_course', as: 'public_index_course'

  get 'plans/public/:course_id/disciplinas', to: 'plans#public_disciplinas', as: 'public_disciplinas'
  post 'plans/public/:course_id/disciplinas', to: 'plans#public_disciplina_planos', as: 'public_disciplina_planos'

  get 'plans/public/:course_id/:discipline_id/planos', to: 'plans#public_curso_disciplina_planos', as: 'public_curso_disciplina_planos'
  # post 'plans/public/:course_id/:discipline_id/planos', to: 'plans#public_curso_disciplina_planos', as: 'public_curso_disciplina_planos'

  get 'plans/publico/index', to: 'plans#publico_index', as: 'publico_index'
  post 'plans/publico/index', to: 'plans#publico_index_planos', as: 'publico_index_planos'
  get 'plans/admin/enviar_aviso_nupe', to: 'plans#enviar_aviso_nupe', as: 'admin_enviar_aviso_nupe'
  match '/pesquisar' => 'plans#pesquisar', as: 'pesquisar_planos', via: [:get, :post]

  # Coordenação de curso
  match '/ofertas_coordenador' => 'offers#pesquisar', as: 'ofertas_coordenador', via: [:get, :post]
  match '/ofertas_coordenador/enviar_aviso_plano_pendente' => 'offers#enviar_aviso_plano_pendente', as: 'coor_enviar_aviso_plano_pendente', via: [:get]
  match '/ofertas_coordenador/enviar_aviso_planos_pendentes' => 'offers#enviar_aviso_plano_pendente', as: 'coor_enviar_aviso_planos_pendentes', via: [:get]

  resources :grid_disciplines
  resources :grids, except: [:destroy] do
    member do
      get 'copy'
    end
    collection do
      get :importar
      post  :importar
    end
    resources :grid_disciplines
  end
  resources :turmas
  resources :course_offers
  resources :courses
  resources :course_modalities
  resources :course_formats
  resources :disciplines, path: 'disciplinas'
  resources :permissao_telas
  resources :permissaos
  resources :perfils
  resources :roles
  resources :perfil_roles, except: [:show]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Configurar para que a tela inicial seja a tela de login, caso não esteja autenticado
  devise_for :users, 
    :controllers => {:registrations => "registrations" },
    skip: [:sessions]
    as :user do
      get 'login', to: 'devise/sessions#new', as: :new_user_session
      post 'login', to: 'devise/sessions#create', as: :user_session
      match 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
  end
  # unauthenticated do
  #   as :user do
  #     root to: 'devise/sessions#new'
  #   end
  # end

  resources :users do
    collection do
      put 'update_perfils'
    end
  end

  # Interface para acessar as tarefas em background através do sidekiq
  # authenticate :user, lambda { |u| u.admin? } do
  #   mount Sidekiq::Web => '/sidekiq' if Rails.env.production? #|| Rails.env.staging?
  # end

  # endereço para ver os e-mails no ambiente de aprovação (staging)
  # mount LetterOpenerWeb::Engine, at: "/mails" if Rails.env.staging? || Rails.env.development?

  root to: 'visitors#index'

end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :offer_discipline
  belongs_to :user, :class_name => 'User'
  belongs_to :user_parecer, :class_name => 'User', optional:true
  belongs_to :coordenador, optional:true

  # attr_accessor :ementa, :objetivo_geral, :bib_geral, :bib_espec

  validates :offer_discipline_id, presence:true,
    if: Proc.new { |a| a.analise? }

  validates :obj_espe, :conteudo_prog, :prat_prof, :interdisc, :met_tec, :met_met, :avaliacao, :cronograma, :atendimento,
    html: { presence: true },
    if: Proc.new { |a| a.analise? }

  validates :ead_percentual_definido, presence:true, if: Proc.new { |a| a.analise? &&
    !a.offer_discipline.ead_percentual_maximo.nil? && !a.offer_discipline.ead_percentual_maximo.eql?(0)
  }, :on => :create

  # validates :ementa, presence:true, if: Proc.new { |a| a.analise? && a.offer_discipline.grid_discipline.discipline.especial? }
  # validates :objetivo_geral, presence:true, if: Proc.new { |a| a.analise? && a.offer_discipline.grid_discipline.discipline.especial? }
  # validates :bib_geral, presence:true, if: Proc.new { |a| a.analise? && a.offer_discipline.grid_discipline.discipline.especial? }
  # validates :bib_espec, presence:true, if: Proc.new { |a| a.analise? && a.offer_discipline.grid_discipline.discipline.especial? }

  accepts_nested_attributes_for :offer_discipline

  def decorate
    @decorate ||= PlanDecorator.new self
  end

  def self.em_analise
    where(analise: true, aprovado:false, reprovado:false)
  end

  def self.aprovados
    where(analise: true, aprovado:true, reprovado:false)
  end

  def self.reprovados
    where(analise: true, aprovado:false, reprovado:true)
  end

end

app/helpers/plans_helper.rb
module PlansHelper

  def nenhum_plano_em_analise? offer_discipline_id
    Plan.where(offer_discipline_id: offer_discipline_id, active:true).
      where(analise:true).where(aprovado:false, reprovado:false).empty? unless offer_discipline_id.nil? || offer_discipline_id.blank?
  end

  def plano_sendo_editado? offer_discipline_id
    !Plan.where(offer_discipline_id: offer_discipline_id, active:true).
      where(analise:false).where(aprovado:false, reprovado:false).empty? unless offer_discipline_id.nil? || offer_discipline_id.blank?
  end

  def planos_por_disciplina offer_discipline_id
    Plan.joins(offer_discipline: {offer: { grid: :course }}).
      where('plans.active is true').
      where('offer_disciplines.id = ?', offer_discipline_id).
      where('offer_disciplines.user_id = ?', current_user.id) if user_signed_in? && !offer_discipline_id.nil?
  end

  def ultimo_plano_aprovado_por_disciplina offer_discipline_id
    Plan.joins(offer_discipline: {offer: { grid: :course }}).
      where('plans.active is true').
      where(aprovado:true).
      where('plans.user_id is not null').
      where('offer_disciplines.user_id is not null').
      where('offer_disciplines.id = ?', offer_discipline_id).
      order(versao: :desc).first if !offer_discipline_id.nil?
  end

  def ultimo_plano_por_disciplina offer_discipline_id
    Plan.joins(offer_discipline: {offer: { grid: :course }}).
      where('plans.active is true').
      where('plans.user_id is not null').
      where('offer_disciplines.user_id is not null').
      where('offer_disciplines.id = ?', offer_discipline_id).
      order(versao: :desc).first if !offer_discipline_id.nil?
  end

  # def aprovados_por_disciplina planos
  #   planos.where(aprovado:true).count
  # end
  #
  # def reprovados_por_disciplina planos
  #   planos.where(reprovado:true).count
  # end
  #
  # def analise_por_disciplina planos
  #   planos.where(analise:true, aprovado:false, reprovado:false).count
  # end
  #
  # def editando_por_disciplina planos
  #   planos.where(analise:false, aprovado:false, reprovado:false).count
  # end

  def ultimo_status_planos analise, aprovado, reprovado, professor = nil
    lista = []
    if !professor.nil?
      ultimos_planos = Plan.select('offer_discipline_id, MAX(versao) AS versao').joins(:offer_discipline).
        group(:offer_discipline_id).where(active:true).where('offer_disciplines.user_id = ?', professor.id)
    else
      ultimos_planos = Plan.select('offer_discipline_id, MAX(versao) AS versao').
        group(:offer_discipline_id).where(active:true)
    end

    ultimos_planos.each do |plano|
      plano = Plan.find_by(offer_discipline_id: plano.offer_discipline_id, versao: plano.versao)
      lista << plano if plano.analise.eql?(analise) && plano.aprovado.eql?(aprovado) && plano.reprovado.eql?(reprovado)
    end
    lista
  end

  # Todos os planos aprovados
  def planos_aprovados professor = nil
    if user_signed_in?
      ultimo_status_planos(true, true, false, professor)
    end
  end

  # Todos os planos reprovados
  def planos_reprovados professor = nil
    if user_signed_in?
      ultimo_status_planos(true, false, true, professor)
      # if professor.nil?
        # Plan.where('plans.active is true').where(analise:true, aprovado:false, reprovado:true)
      # else
        # Plan.where('plans.active is true and plans.user_id = ?', professor.id).where(analise:true, aprovado:false, reprovado:true)
      # end
    end
  end

  # Todos os planos em análise
  def planos_analisando professor = nil
    if user_signed_in?
      ultimo_status_planos(true, false, false, professor)
      # if professor.nil?
      #   Plan.where('plans.active is true').where(analise:true, aprovado:false, reprovado:false)
      # else
      #   Plan.where('plans.active is true and plans.user_id = ?', professor.id).where(analise:true, aprovado:false, reprovado:false)
      # end
    end
  end

  # Todos os planos sendo editado
  def planos_editando professor = nil
    if user_signed_in?
      ultimo_status_planos(false, false, false, professor)
    end
  end

  # Todos os planos
  def planos_total professor = nil
    if user_signed_in?
      lista = []

      if !professor.nil?
        ultimos_planos = Plan.select('offer_discipline_id, MAX(versao) AS versao').
        group(:offer_discipline_id).where(active:true, user: professor)
      else
        ultimos_planos = Plan.select('offer_discipline_id, MAX(versao) AS versao').
        group(:offer_discipline_id).where(active:true)
      end

      ultimos_planos.each do |plano|
        lista << Plan.find_by(offer_discipline_id: plano.offer_discipline_id, versao: plano.versao)
      end

      lista
    end
  end

  # Utilizado para passar parâmetros ao enviar por e-mail
  # Ex: PlanoEnsinoMailer.enviar_email_aviso_nupe(get_options_email).deliver_later!
  # def get_options_email
  #   options = {
  #     id: @plan.id,
  #     offer_id: @plan.offer_discipline.offer_id,
  #     offer_discipline_id: @plan.offer_discipline_id,
  #     curso: "#{@plan.offer_discipline.grid_discipline.grid.course.sigla} - #{@plan.offer_discipline.grid_discipline.grid.course.decorate.name}",
  #     disciplina: @plan.offer_discipline.grid_discipline.discipline.decorate.title,
  #     turma: @plan.offer_discipline.offer.turma,
  #     professor: @plan.user.name,
  #     versao: @plan.decorate.versao,
  #     dtcreated: @plan.created_at.strftime('%d/%m/%Y')
  #   }
  # end

end

app/views/plans/_form.html.erb
<%= bootstrap_form_for(plan, url: url, local:true, html: { class: "", role: "form", id: 'plans_form' }) do |f| %>
  <%= error_messages_for(plan) %>

  <%= f.hidden_field :versao %>

  <div class="row">
    <div class="col-md-9 col-lg-9">

      <div class="col-md-12">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#ementa" data-toggle="tab">Ementa</a></li>
          <li><a href="#objetivos" data-toggle="tab">Objetivos</a></li>
          <li><a href="#conteudos" data-toggle="tab">Conteúdo</a></li>
          <li><a href="#pratica" data-toggle="tab">Prática</a></li>
          <li><a href="#metodologias" data-toggle="tab">Metodologias</a></li>
          <li><a href="#avaliacao" data-toggle="tab">Avaliação/<br>Recuperação</a></li>
          <li><a href="#interdisci" data-toggle="tab">Interdisciplinaridade</a></li>
          <li><a href="#cronograma" data-toggle="tab">Cronograma</a></li>
          <li><a href="#info_adicionais" data-toggle="tab">Observações</a></li>
          <li><a href="#atendimento" data-toggle="tab">Atendimento AA</a></li>
          <li><a href="#referencias" data-toggle="tab">Referências</a></li>
        </ul>
      </div>

      <div class="col-md-12">
        <hr style="margin-top: 5px; margin-bottom: 10px;">
        <div class="tab-content">
          <div id="ementa" class="tab-pane fade in active">
            <% if plan.offer_discipline.grid_discipline.discipline.especial? %>
              <!-- <= f.fields_for :offer_discipline do |a| %>
                <= a.fields_for :grid_discipline do |b| %>
                  <= b.text_area :ementa, id: :plan_offer_discipline_grid_discipline_ementa, rows: 8, data: {provider: :none} %>
                < end %>
              < end %> -->
              <%= label_tag :ementa, t('activerecord.attributes.grid_discipline.ementa'), class: 'control-label' %>
              <%= text_area_tag :ementa, params[:ementa] || plan.offer_discipline.grid_discipline.ementa, id: :plan_ementa, rows: 8, data: {provider: :none}, class: 'form-control', placeholder: 'Ementa do componente curricular', autofocus:true %>
            <% else %>
              <div class="form-group">
                <div class="html_safe_div">
                  <p class="header"><%= label_tag :ementa, t('activerecord.attributes.grid_discipline.ementa'), class: 'control-label' %></p>
                  <%= plan.offer_discipline.grid_discipline.decorate.ementa %>
                </div>
              </div>
            <% end %>
          </div>

          <div id="objetivos" class="tab-pane fade in">
            <% if plan.offer_discipline.grid_discipline.discipline.especial? %>
              <%= label_tag :objetivo_geral, t('activerecord.attributes.grid_discipline.objetivo_geral'), class: 'control-label' %>
              <%= text_area_tag :objetivo_geral, params[:objetivo_geral] || plan.offer_discipline.grid_discipline.objetivo_geral, id: :plan_objetivo_geral, rows: 8, data: {provider: :none}, class: 'form-control', placeholder: 'Objetivo geral do componente curricular', autofocus:true %>
            <% else %>
              <div class="form-group">
                <div class="html_safe_div">
                  <p class="header"><%= label_tag :objetivo_geral, t('activerecord.attributes.grid_discipline.objetivo_geral'), class: 'control-label' %></p>
                  <%= plan.offer_discipline.grid_discipline.decorate.objetivo_geral.html_safe %>
                </div>
              </div>
            <% end %>

            <%= f.text_area :obj_espe, id: :plan_obj_espe, rows: 8, data: {provider: :none} %>
          </div>

          <div id="conteudos" class="tab-pane fade in">
            <%= f.text_area :conteudo_prog, id: :plan_conteudo_prog, rows: 10, data: {provider: :none} %>
          </div>

          <div id="pratica" class="tab-pane fade in">
            <%= f.text_area :prat_prof, id: :plan_prat_prof, rows: 10, data: {provider: :none} %>
          </div>

          <div id="metodologias" class="tab-pane fade in">
            <%= f.text_area :met_tec, id: :plan_met_tec, rows: 6, data: {provider: :none} %>
            <%= f.text_area :met_met, id: :plan_met_met, rows: 6, data: {provider: :none} %>
          </div>

          <div id="avaliacao" class="tab-pane fade in">
            <%= f.text_area :avaliacao, id: :plan_avaliacao, data: {provider: :none}, rows: 15 %>
          </div>

          <div id="interdisci" class="tab-pane fade in">
            <%= f.text_area :interdisc, id: :plan_interdisc, rows: 10, data: {provider: :none} %>
          </div>

          <div id="cronograma" class="tab-pane fade in">
            <%= f.text_area :cronograma, id: :plan_cronograma, rows: 10, data: {provider: :none} %>
          </div>

          <div id="info_adicionais" class="tab-pane fade in">
            <%= f.text_area :observacoes, id: :plan_observacoes, rows: 6, data: {provider: :none} %>
          </div>

          <div id="atendimento" class="tab-pane fade in">
            <%= f.text_area :atendimento, id: :plan_atendimento, rows: 1, data: {provider: :none} %>
          </div>

          <div id="referencias" class="tab-pane fade in">
            <% if plan.offer_discipline.grid_discipline.discipline.especial? %>
              <%= label_tag :bib_geral, t('activerecord.attributes.grid_discipline.bib_geral'), class: 'control-label' %>
              <%= text_area_tag :bib_geral, params[:bib_geral] || plan.offer_discipline.grid_discipline.bib_geral, id: :plan_bib_geral, rows: 8, data: {provider: :none}, class: 'form-control', placeholder: 'Referências básicas', autofocus:true %>
              <%= label_tag :bib_espec, t('activerecord.attributes.grid_discipline.bib_espec'), class: 'control-label' %>
              <%= text_area_tag :bib_espec, params[:bib_espec] || plan.offer_discipline.grid_discipline.bib_espec, id: :plan_bib_geral, rows: 8, data: {provider: :none}, class: 'form-control', placeholder: 'Referências complementares', autofocus:true %>
            <% else %>
              <div class="form-group">
                <div class="html_safe_div">
                  <p class="header"><%= label_tag :bib_geral, t('activerecord.attributes.grid_discipline.bib_geral'), class: 'control-label' %></p>
                  <%= plan.offer_discipline.grid_discipline.decorate.bib_geral %>
                </div>
              </div>
              <div class="form-group">
                <div class="html_safe_div">
                  <p class="header"><%= label_tag :bib_espec, t('activerecord.attributes.grid_discipline.bib_espec'), class: 'control-label' %></p>
                  <%= plan.offer_discipline.grid_discipline.decorate.bib_espec %>
                </div>
              </div>
            <% end %>
          </div>

        </div>
      </div>

    </div>

    <div class="col-md-3 col-ld-3">
      <%# Se for atividade remota então não deve aparecer para o professor selecionar %>
      <% if !@plan.offer_discipline.ead_percentual_maximo.nil? && @plan.offer_discipline.ead_percentual_maximo > 0 %>
        <% ead_definido = @plan.ead_percentual_definido.nil? ? nil : "#{@plan.ead_percentual_definido} %" %>
        
        <ul class=<%= (('remotas').eql? @plan.offer_discipline.offer.type_offer) ? 'list-group hidden' : 'list-group' %>>
          <li class="list-group-item list-group-item-info" title="Atividade Não Presencial">(%) ANP</li>
          <li class="list-group-item">
            <% if !('remotas').eql? @plan.offer_discipline.offer.type_offer %>
              <%= f.select :ead_percentual_definido,
                  options_for_select((0..@plan.offer_discipline.ead_percentual_maximo).step(5).collect {|a| "#{a} %"}, "#{ead_definido} %" ),
                  { hide_label:true, include_blank: 'Percentual de C.H à distância' },
                  { class: 'form-control input-sm', wrapper: { style: 'margin-bottom: 0;'}} %>
            <%else%>
            <%= f.select :ead_percentual_definido,
                  options_for_select((0..@plan.offer_discipline.ead_percentual_maximo).step(5).collect {|a| "#{a} %"}, "#{@plan.offer_discipline.ead_percentual_maximo} %" ),
                  { hide_label:true, include_blank: 'Percentual de C.H à distância' },
                  { class: 'form-control input-sm', wrapper: { style: 'margin-bottom: 0;'}} %>
            <% end %>
          </li>
        </ul>
      <% end %>
      <ul class="list-group">
        <%= render 'list_group_items', plan: @plan %>
        <div class="alert alert-warning well-sm">
          <u><p><strong>Observações</strong></p></u>
          Ao <code>Salvar e enviar para análise</code>, uma nova versão somente poderá ser criada após o plano ser analisado.
        </div>
      </ul>
    </div>

  </div>

  <div class="fixed-on-bottom">
    <%= button_tag type: "submit", class: "btn btn-sm btn-primary", name: 'commit', title: 'Salvar e continuar na tela' do %>
      <i class="fa fa-envelope-o pull-left" aria-hidden="true"></i>
      Salvar
    <% end %>
    <%= button_tag type: "submit", class: "btn btn-sm btn-warning", name: 'commit_depois', title: 'Salvar e continuar mais tarde.' do %>
      <i class="fa fa-envelope-o pull-left" aria-hidden="true"></i>
      Salvar e editar depois
    <% end %>
    <%= button_tag type: "submit", class: "btn btn-sm btn-success", name: 'commit_analise', title: "Salvar, fechar plano, enviar para análise." do %>
      <i class="fa fa-2 fa-check pull-left"></i>
      Salvar e enviar para análise
    <% end %>
    <!-- <= link_to offer_offer_discipline_plans_path(offer_discipline_id: @plan.offer_discipline_id), class: 'btn btn-default' do %>
      <i class="fa fa-2 fa-arrow-circle-left"></i>
      Voltar sem salvar
    < end %> -->

  </div>

<% end %>

app/views/plans/_form_search.html.erb
<%= form_for planos_curso_path, method: :get, html: {class: ''} do |f| %>
  <div class="form-group col-md-3">
    <%= select_tag :course_id_tag, options_for_select(cursos_por_professor.map { |k,v| [v, k]}, params[:course_id] ),
        id: :course_id_tag, class: 'select2 input-sm', prompt:'Selecione o curso', required:true, autofocus:true %>
  </div>
  <div class="form-group col-md-3">
    <%= select_tag :discipline_id_tag, options_for_select(disciplinas_curso_e_por_professor.map { |k,v| [v, k]}, params[:discipline_id] ),
        id: :discipline_id_tag, class: 'select2 input-sm', prompt:'Selecione o componente curricular' %>
  </div>
  <div class="form-group col-md-2">
    <%= text_field_tag :ano_tag, params[:ano_tag], id: :ano_tag, class: 'form-control input-sm', placeholder: 'Ano' %>
  </div>
  <%= submit_tag 'Pesquisar', class: 'btn btn-sm btn-primary' %>
<% end %>

app/views/plans/_list_group_items_horarios.html.erb
<li class="list-group-item list-group-item-info">Carga horária</li>
<li class="list-group-item">
  <% if !plan.offer_discipline.ead_percentual_maximo.nil? &&
        !plan.offer_discipline.ead_percentual_maximo.eql?(0) &&
        !plan.ead_percentual_definido.nil? %>

      <% horarios = plan.decorate.carga_horaria_presencial_distancia %>

      <dl class="dl-vertical">
        <dt>Presencial</dt>
        <dd><span class="badge"><%= "#{horarios[:presencial]} - #{horarios[:presencial_aula]}" %></span></dt>
        <dt>À distância</dt>
        <dd><span class="badge"><%= "#{horarios[:distancia]} - #{horarios[:distancia_aula]}" %></span></dt>
      </dl>
  <% else %>
    <p>
      <span class="badge"><%= plan.offer_discipline.decorate.carga_horaria_hora_text %></span>
      <span class="badge"><%= plan.offer_discipline.decorate.carga_horaria_aula_text %></span>
    </p>
  <% end %>
</li>

app/views/plans/_list_group_items_parecer.html.erb
<li class="list-group-item list-group-item-success">
  Parecer
</li>
<li class="list-group-item">
  <p>
    <%= @plan.decorate.situacao %>
    <span class="badge pull-right">
      <%= "v#{@plan.decorate.versao}" %>
    </span>
  </p>
  <!-- Apenas se for administrador  -->
  <% if is_admin? && @plan.analise? %>
      <%= link_to admin_enviar_aviso_nupe_path(plan_id: @plan.id), class: 'btn btn-block btn-default' do %>
          <i title="Apenas para administradores" class="fa fa-lock pull-left"></i>
          Enviar aviso ao NUPE
      <% end %>
  <% end %>

  <% if user_signed_in? && @plan.analise? %>
    <hr>
    <% if (can? :aprovar_reprovar, Plan) %>
      <%= form_for(@plan, url: aprovar_offer_offer_discipline_plan_path, method: :post) do |f| %>
        <div class="form-group">
          <%= f.label :parecer, class: 'control-label' %>
          <%= f.text_area :parecer, class: 'form-control', rows: 10, autofocus:true %>
        </div>
        <%= button_tag type: "submit", class: "btn btn-success btn-block" do %>
          <i class="fa fa-2 fa-check pull-left"></i>
          Aprovar
        <% end %>
        <%= button_tag type: "submit", class: "btn btn-danger btn-block", name: 'commit_reprovar' do %>
          <i class="fa fa-2 fa-window-close pull-left"></i>
          Com pendências
        <% end %>
      <% end %>
    <% else %>
      <%= label_tag :parecer, 'Parecer', class: 'control-label' %>
      <%= text_area_tag :parecer, @plan.parecer, rows: 10, disabled:true, class: 'form-control'%>
    <% end %>
  <% end %>
</li>
<% if user_signed_in? && !@plan.user_parecer.nil? %>
  <li class="list-group-item list-group-item-info">
    <p>Analisado por:</p>
    <p><strong><%= @plan.user_parecer.name %></strong></p>
  </li>
<% end %>

app/views/plans/aprovacao.html.erb
  <!-- <= form_for get_planos_aprovar_path, method: :get, html: {class: ''} do |f| %>
    <span class="badge">
      <= f.check_box :analise,
            id: :analise, class: 'form-check-input' %>
      <= label_tag :analise, 'Planos em análise' %>
    </span>

    <span class="badge">
      <= f.check_box :aprovado,
            id: :aprovado, class: 'form-check-input' %>
      <= label_tag :aprovado, 'Planos aprovados' %>
    </span>

    <span class="badge">
      <= f.check_box :reprovado,
            id: :reprovado, class: 'form-check-input' %>
      <= label_tag :reprovado, 'Planos reprovados' %>
    </span>

  <= submit_tag 'Pesquisar', class: 'btn btn-sm btn-primary' %>
< end %>

<hr> -->

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Analisar planos</h3>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <%= content_tag :table, id: 'plans_datatable', class: 'table table-striped table-bordered', data: { url: get_planos_aprovar_path(format: :json)} do %>
        <thead>
          <tr>
            <th>Oferta</th>
            <th>Componente curricular</th>
            <th>Professores</th>
            <th>Versão</th>
            <th>Situação</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody></tbody>
      <% end %>
    </div>

  </div>
</div>

app/views/plans/edit.html.erb
<%- model = Plan %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= t('helpers.titles.edit', model: model.model_name.human.downcase) %>
    </h3>
  </div>
  <div class="panel-body">
    <%= render 'form', plan: @plan, url: offer_offer_discipline_plan_path %>
  </div>
  <!-- <div class="panel-footer">
    <= @plan.decorate.link_index %>
    <= @plan.decorate.link_show %>
  </div> -->
</div>

app/views/plans/new.html.erb
<%- model = Plan %>

<%= render 'form', plan: @plan, url: offer_offer_discipline_plans_path %>
<!-- <= link_to t('helpers.links.back'), offer_offer_discipline_plans_path(offer_discipline_id: params[:offer_discipline_id]) %> -->